[[protocols]]
name = 'Formuler F4'
protocol = 'nec'
header_pulse = 4500
header_space = 4500
bit_pulse = 600
bit_0_space = 500
bit_1_space = 1600
bits = 32
margin = 300
trailer_pulse = 600
[protocols.scancodes]
0x33 = "KEY_SUSPEND"
0x34 = "KEY_F1"
0x35 = "KEY_F2"
0x36 = "KEY_F3"
0xa = "KEY_MUTE"
0x1 = "KEY_1"
0x2 = "KEY_2"
0x3 = "KEY_3"
0x4 = "KEY_4"
0x5 = "KEY_5"
0x6 = "KEY_6"
0x7 = "KEY_7"
0x8 = "KEY_8"
0x9 = "KEY_9"
0x17 = "KEY_PREVIOUS"
0x0 = "KEY_0"
0x60 = "KEY_NEXT"
0x6c = "KEY_VOLUMEUP"
0x6d = "KEY_VOLUMEDOWN"
0x54 = "KEY_CONTEXT_MENU"
0x1b = "KEY_EPG"
0x6a = "KEY_CHANNELUP"
0x6b = "KEY_CHANNELDOWN"
0x1a = "KEY_MENU"
0x1e = "KEY_EXIT"
0x51 = "KEY_INFO"
0x57 = "KEY_CLOSE"
0xb = "KEY_UP"
0x11 = "KEY_RIGHT"
0xe = "KEY_DOWN"
0x10 = "KEY_LEFT"
0xd = "KEY_OK"
0x52 = "KEY_RED"
0x63 = "KEY_GREEN"
0x62 = "KEY_YELLOW"
0x61 = "KEY_BLUE"
0x21 = "KEY_REWIND"
0x23 = "KEY_PLAYPAUSE"
0x24 = "KEY_FORWARD"
0x6e = "KEY_HELP"
0x25 = "KEY_AUDIO"
0x26 = "KEY_STOP"
0x27 = "KEY_RECORD"
0x28 = "KEY_LIST"
0x29 = "KEY_TEXT"
0x30 = "KEY_TV"
0x31 = "KEY_RADIO"
0x32 = "KEY_FAVORITES"
