---

- name: Create K8s network directory
  ansible.builtin.file:
    path: /etc/kubernetes/network
    state: directory

- name: Copy Calico YAML files
  ansible.builtin.get_url:
    url:
      https://raw.githubusercontent.com/projectcalico/calico/v3.24.5/manifests/calico.yaml
    dest: /etc/kubernetes/network/calico.yml

- name: Check Calico daemonset is working
  ansible.builtin.shell:
    kubectl --kubeconfig={{ kubeadmin_config }} get ds -A | grep calico
  run_once: true
  register: check_net
  ignore_errors: true
  changed_when: false

- name: Create Calico network daemonset
  ansible.builtin.command: |
    kubectl apply \
    --kubeconfig={{ kubeadmin_config }} \
    -f /etc/kubernetes/network/
  run_once: true
  when: check_net is failed
