---

network:
  ethernets:
    eth0:
      dhcp4: false
      dhcp6: false
  bridges:
    br0:
      interfaces: [eth0]
      dhcp4: false
      dhcp6: false
      addresses: [192.168.0.239/24]
      macaddress: 02:00:00:1e:03:01
      mtu: 1500
      routes:
        - to: default
          via: 192.168.0.1
          metric: 100
          on-link: true
      nameservers:
        addresses: [8.8.8.8]
      parameters:
        stp: false
        forward-delay: 4
  version: 2
